### ISSUE TITLE
pocket generation chance

### ISSUE THREAD

**Issue by TheUntamed** [MapperTV/embellishcraft-bop#1]
the config says the chance value has to be between 0 and 100. Can it also be between 0 and 1? For example 0.5 or 0.01?

I would like to reduce the amount of clusters drastically and increase the size to make them fit the large cluster generation the _Quark_ mod generates.

**Comment by MapperTV** [comment]
It must be a integer, so 1 is the lowest value. At 1 it should be quite rare already.

Also this is not the good mod, the BoP addon doesn't have any world gen.
