### ISSUE TITLE
[1.15.2][Bug Report] Mining a cherry crate drops cherry stairs

### ISSUE THREAD

**Issue by ghost** [MapperTV/embellishcraft-bop#3]
Title explains what is wrong... No other problems and all mods are up to date... Production error?

**Comment by MapperTV** [comment]
Should be fixed in latest release.

**Comment by MapperTV** [comment]
Forgot to apply the fix in the latest release... Will do another one asap.

**Comment by MapperTV** [comment]
Fixed in 2.1.1.
